export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const CLEAR_CART_FROM_ITEMS = 'CLEAR_CART_FROM_ITEMS';
export const EDIT_ITEM_CART = 'EDIT_ITEM_CART';