//cart actions
export const cartTypes = {
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  CLEAR_CART_FROM_ITEMS: "CLEAR_CART_FROM_ITEMS",
  EDIT_ITEM_CART: "EDIT_ITEM_CART",
};
