//Filter Actions
export const filterTypes = {
  FILTER_INPUT: "FILTER_INPUT",
  FILTER_CATEGORY: "FILTER_CATEGORY",
  FILTER_COMPANY: "FILTER_COMPANY",
  FILTER_PRICE: "FILTER_PRICE",
  FILTER_PRODUCTS: "FILTER_PRODUCTS",
};
